version: '3'

services:
  #redis
  redis:
    hostname: redis
    image: redis:5.0.6-alpine
    # 开启持久化，并设置密码
    command: redis-server --appendonly yes --requirepass "redis123"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      
  # redis_exporter    
  redis_exporter:
    image: oliver006/redis_exporter:v1.3.1-alpine
    hostname: redis_exporter
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - REDIS_ADDR=redis://redis:6379
      - REDIS_PASSWORD=redis123
    restart: unless-stopped
